### ISSUE TITLE
建议修改限定依赖版本范围

### ISSUE THREAD

**Issue by huhuime** [cmdparkour/vue-admin-box#11]
报错`Uncaught SyntaxError: The requested module '/node_modules/.vite/vue.js?v=9f6682f3' does not provide an export named 'createElementBlock'`

**Comment by cmdparkour** [comment]
已收到，后续会把更新速度快的模块，限制版本

**Comment by huhuime** [comment]
> 已收到，后续会把更新速度快的模块，限制版本

重新取了下最新版本，貌似这样也能用了
`"dependencies": {
    "@vueuse/core": "^6.1.0",
    "axios": "^0.22.0",
    "element-plus": "^1.1.0-beta.19",
    "mockjs": "^1.1.0",
    "normalize.css": "^8.0.1",
    "nprogress": "^0.2.0",
    "throttle-debounce": "^3.0.1",
    "vue": "^3.2.16",
    "vue-router": "^4.0.11",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.9.3",
    "unplugin-element-plus": "^0.1.0",
    "sass": "^1.42.1",
    "vite": "^2.6.4",
    "vite-plugin-mock": "^2.9.6"
  }`
不过，需要修改引入element-plus的css部分变成`import 'element-plus/dist/index.css'`
