### ISSUE TITLE
Demo site is different from github code

### ISSUE THREAD

**Issue by ITKHMER** [cmdparkour/vue-admin-box#14]
The demo runs well. But when I use source code from Github or Gitee, there are some problems. 
1-DialogBox cannot move up/down. 
2-Missing the green loading icon in top-right. Is it different version?

**Comment by cmdparkour** [comment]
I‘m sorry for it, the demo website is not the last versions in it, and it not the CI/CD,  the last time i check the version to the last version with element-plus, so something maybe warning in the performance, thank for your issues, and i will finish it today

**Comment by cmdparkour** [comment]
the first is fixed, and the second bug i can't find the position, you need to tell me maybe in a photo

**Comment by ITKHMER** [comment]
This is the location of the green loading icon. Thank you for your effort making this amazing template available. 


![2021-11-01](https://user-images.githubusercontent.com/93175803/139616867-be7a6855-3924-4015-b7a0-44c4bac14f33.png)

**Comment by cmdparkour** [comment]
let me do it, maybe one hour later, you can see the change of the project.

**Comment by cmdparkour** [comment]
maybe it not a bug about it , the icon is meaning the website is loading and when it loading as well, it will be hidden.
