### ISSUE TITLE
Request for Filter box below the table header

### ISSUE THREAD

**Issue by ITKHMER** [cmdparkour/vue-admin-box#15]
Hi, 
Can you please add filter box below the table header? Please find the sample below:
https://raw.githubusercontent.com/rubanraj54/vue-bootstrap4-table/develop/src/assets/img/demo.gif

Thank you!

**Comment by cmdparkour** [comment]
it's not a basic function in the vue-admin-box, you can fix it by yourself, maybe it can be supported a few months later, but not now, i need to do more things about the develop experience and the performance about the big back-end. You can make a basic component as you want.

**Comment by cmdparkour** [comment]
the issue will open until i have time to do it. It's a good idea to search.

**Comment by cmdparkour** [comment]
i think maybe it will be a common component to you and you can fixed it by yourself. As a frame, it should not be a choose for everyone, the frame should keep clean at first.
