### ISSUE TITLE
打开多个tabs会出现严重卡顿，只能刷新界面解决

### ISSUE THREAD

**Issue by miss-tree** [cmdparkour/vue-admin-box#16]

**Comment by cmdparkour** [comment]
can you push me a online website or a video to show the problem

**Comment by cmdparkour** [comment]
I don't find the same bugs in my demo website, maybe its the bug about your page. and you fuck some Calculation of large amount of data, not unloaded

**Comment by cmdparkour** [comment]
when i open 42 tabs, but i don't find the question here.

**Comment by miss-tree** [comment]
代码是10月26号拉的代码。发现了，是因为在点击防抖界面出现了一个 callback is not a function 报错，导致界面卡顿

**Comment by cmdparkour** [comment]
确认存在问题，我看下

**Comment by cmdparkour** [comment]
fixed it ,you can check it and open or close with comment
