### ISSUE TITLE
element-plus 升级到 1.2.0-beta.2后，右上角的Tab样式异常

### ISSUE THREAD

**Issue by aliang888** [cmdparkour/vue-admin-box#18]
element-plus 升级到 1.2.0-beta.2后，右上角的Tab样式异常
![1](https://user-images.githubusercontent.com/19453262/140702613-819e9d66-805d-4204-8191-7139fbd61f33.png)

**Comment by ITKHMER** [comment]
It's the same to my issue (https://github.com/cmdparkour/vue-admin-box/issues/17#issue-1046951136) which caused by breaking change of element plus 1.2.0 (https://github.com/element-plus/element-plus/discussions/4060)

**Comment by cmdparkour** [comment]
fixed it
