### ISSUE TITLE
Form validation not refresh

### ISSUE THREAD

**Issue by ITKHMER** [cmdparkour/vue-admin-box#20]
1st validation is correct when we submit blank form. However, after changing the data in select (dropdown), the validation alert is still there.
![photo_2021-11-12_09-45-18](https://user-images.githubusercontent.com/93175803/141400922-5dab3c77-1291-41a1-b3c1-99c3ca2fee70.jpg)

**Comment by cmdparkour** [comment]
the bug you should submit to element-plus, the framework don't care the bug about element-plus
