### ISSUE TITLE
Error detected by console 

### ISSUE THREAD

**Issue by ITKHMER** [cmdparkour/vue-admin-box#26]
I noticed the following error when inspect:

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT (https://hm.baidu.com/hm.js?bd78bc908e66174e7dde385bf37cb4c1)

index.vue:160 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelector')
    at setPosition (index.vue:160)
    at index.vue:153

Looks like it relates to src/layout/Tabs/index.vue (line 160)
Please help checking. Thank you!

**Comment by yirius** [comment]
you can fix this with comment out function baidu in src/utils/system/statistics.ts

**Comment by cmdparkour** [comment]
this is a website api for record something about use , you can hidden it for yourself. It's not a  required choice.

**Comment by ITKHMER** [comment]
The following error is still there after comment out the baidu script:

index.vue:160 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelector')
at setPosition (index.vue:160)
at index.vue:153 

Looks like it relates to src/layout/Tabs/index.vue (line 160)
Please help checking again. Thank you!
