### ISSUE TITLE
打包后页面空白

### ISSUE THREAD

**Issue by cklishandsome** [cmdparkour/vue-admin-box#27]
1.打包
npm run build;
2. 开服务
serve dist;
3.页面空白

**Comment by cmdparkour** [comment]
自查一下资源引用路径，如果路径不对，配置一下vite.config.ts

**Comment by cklishandsome** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cmdparkour/vue-admin-box"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月8日(星期三) 晚上9:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cmdparkour/vue-admin-box] 打包后页面空白 (Issue #27)





 
自查一下资源引用路径，如果路径不对，配置一下vite.config.ts

**Comment by cklishandsome** [comment]
资源引用路径是对的，js图片等资源都能加载，开发模式没问题，就是打包页面是空白的


我看了是 src\router\createNode.ts 这个不对
在路由配置中
// 路由跳转后的监听操作

router.afterEach((to, _from) =&gt; {
&nbsp; const keepAliveComponentsName = store.getters['keepAlive/keepAliveComponentsName'] || []
&nbsp; const name = to.matched[to.matched.length - 1].components.default.name
...
}


name&nbsp; 的值为undefined&nbsp;&nbsp;


我换成&nbsp; [js版本，无国际化] 里的 createNode.js 的代码 就好了




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "cmdparkour/vue-admin-box"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月8日(星期三) 晚上9:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cmdparkour/vue-admin-box] 打包后页面空白 (Issue #27)





 
自查一下资源引用路径，如果路径不对，配置一下vite.config.ts
