### ISSUE TITLE
添加相关规范建议

### ISSUE THREAD

**Issue by jtfl2008** [cmdparkour/vue-admin-box#3]
希望可以添加相关规范，比如代码规范，提交规范，还有参与项目规范

**Comment by cmdparkour** [comment]
代码这一块，后期应该会加入eslint来进行一次重大改版

**Comment by cmdparkour** [comment]
提交规范的话，会持续坚持0规范提交，不浪费其他愿意参与开源项目维护人员的时间，只要提交的代码能解决实际的问题，能促进框架的迭代生长，我这面审查一次代码，然后在本地自行测试一波，没啥问题就可以合的，到时候每天有一个统一时间来处理这个事，先持续2个月看一下效果吧
