### ISSUE TITLE
子菜单只有一级的时候

### ISSUE THREAD

**Issue by qiguoqiang** [cmdparkour/vue-admin-box#4]
子菜单只有一个，同时子菜单的子菜单有多个，这时候在菜单上只会显示两层菜单，但实际层级是三层
层级如下
```
----menu
    ---menu-1
       ---menu-1-1
       ---menu-1-2
```
这种层级的时候顶层的菜单不会显示，会被menu-1替换，如果添加一个和menu-1平行的menu-2，就会正常显示menu

**Comment by qiguoqiang** [comment]
终于找到了，可以用alwayShow来控制，作者考虑是不是把代码里有些细节的功能写到文档里

**Comment by cmdparkour** [comment]
确实，我把菜单的文档加一下
