### ISSUE TITLE
为什么基础版本项目还是用的1.0版本的element-plus

### ISSUE THREAD

**Issue by cshenger** [cmdparkour/vue-admin-box#42]
我看了vue-admin-box-template 的代码里面的element-plus使用的还是 1.0.2-beta.48 这个版本，后期有升级的计划吗？

**Comment by cmdparkour** [comment]
有的，等手里的项目忙完，再着手跟进这个开源项目，毕竟不是专职开源的

**Comment by cmdparkour** [comment]
已更新至最新
