### ISSUE TITLE
i18n vscode插件没法显示

### ISSUE THREAD

**Issue by Axu96** [cmdparkour/vue-admin-box#49]
![image](https://user-images.githubusercontent.com/28865316/174952441-b5de85ca-920c-4b36-b653-681522f246fd.png)
![FBE958BAAADFBF3B6F5E4309D1F732CE](https://user-images.githubusercontent.com/28865316/174952457-cdab8364-8ed9-41b7-b5a2-f165f04035b3.png)
i18n vscode插件没法显示

**Comment by cmdparkour** [comment]
看下，是不是自己需要配置什么地址，才能生效
