### ISSUE TITLE
tagview多标签切换问题

### ISSUE THREAD

**Issue by Mrjiangqianli** [cmdparkour/vue-admin-box#50]
我在列表页点击进去详情页会传query参数，但我又从详情页点击tag回到列表页，此时详情页未关闭，我又从列表页点击tag回到列表页，我传的参数不见了？？？你源码这样子写肯定会有问题的
<router-link :to="menu.path'" v-if="menu.meta.title">
      {{ $t(menu.meta.title) }}
 </router-link>

**Comment by cmdparkour** [comment]
周末复现一下这个操作，搞一波

**Comment by cmdparkour** [comment]
已修复此问题
