### ISSUE TITLE
动态加载菜单刷新会404

### ISSUE THREAD

**Issue by 337076876** [cmdparkour/vue-admin-box#51]
版本是JS国际版
在router/index.js
方法 addRoutes 中请求后台数据加载菜单

一切都正常,唯一不足的是 F5刷新跳转到404页面。 虽然还是可以点击菜单回到页面,但是考虑到用户体验，还是想问问有什么办法可以修复...

**Comment by cmdparkour** [comment]
参照一下主站，主站修复了

**Comment by 337076876** [comment]
> 参照一下主站，主站修复了

参考路由index.ts 里面的 router.beforeEach  方法么？
