### ISSUE TITLE
npm run dev无法启动

### ISSUE THREAD

**Issue by newwayxp** [cmdparkour/vue-admin-box#55]
The following dependencies are imported but could not be resolved:

  highlight.js (imported by /Users/keyin/code/vite/vue-admin-box/src/views/main/components/mdEditor/index.vue?id=0)

Are they installed?

出现上面的提示

**Comment by tipsbefore** [comment]
the first thing you need to do is : **yarn or npm install**;

**Comment by newwayxp** [comment]
> 
Thank you.
I had used npm install, it looks not like a npm problem.

**Comment by cmdparkour** [comment]
use yarn can help you to fix it.
