### ISSUE TITLE
runtime-core.esm-bundler.js:40   [Vue warn]: Property "data" was accessed during render but is not defined on instance.

### ISSUE THREAD

**Issue by oeliok** [cmdparkour/vue-admin-box#59]
runtime-core.esm-bundler.js:40 
        
       [Vue warn]: Property "data" was accessed during render but is not defined on instance. 
  at <ElTableBody context= {uid: 400, vnode: {…}, type: {…}, parent: {…}, appContext: {…}, …} highlight=false row-class-name=undefined  ... > 
  at <ElTable data= (15) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] > 
  at <ElOverlay mask=true overlay-class=undefined z-index=2015  ... > 
  at <BaseTransition onAfterEnter=fn<afterEnter> onAfterLeave=fn<afterLeave> onBeforeLeave=fn<beforeLeave>  ... > 
  at <Transition name="dialog-fade" onAfterEnter=fn<afterEnter> onAfterLeave=fn<afterLeave>  ... > 
  at <ElDialog title="提示" modelValue=false onUpdate:modelValue=fn  ... > 
  at <Batchrun> 
  at <VueAdminBox$1683044433667 onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > key="/batchmng/batchrun" > 
  at <KeepAlive key=0 include= (4) ['vueAdminBox$1683044430203', 'vueAdminBox$1683044432684', 'vueAdminBox$1683044433115', 'vueAdminBox$1683044433667'] > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="fade-transform" mode="out-in" > 
  at <RouterView> 
  at <ElMain> 
  at <ElContainer> 
  at <ElContainer style= {height: '100vh'} > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <RouterView> 
  at <ElConfigProvider locale= {name: 'zh-cn', el: {…}} > 

作者大大升级一下element-plus的版本吧，好像有bug，我本地想使用
<el-table-column prop="data" label="更多" width="180">
                    <template slot-scope="data">
                        <span style="margin-left: 10px">{{ handledata(data) }}</span>
                    </template>
                </el-table-column>
传入的data为空的对象

**Comment by oeliok** [comment]
我自己也主动升级了，发现管理页面的布局坏了

**Comment by cmdparkour** [comment]
得空，我升级一下

**Comment by cmdparkour** [comment]
已升级至最新版本
