### ISSUE TITLE
axios功能添加在哪

### ISSUE THREAD

**Issue by Apophisdeity** [cmdparkour/vue-admin-box#65]
你好,请问我想加入接口请求,是在vue文件里加axios吗,替换掉options,刚学前端,不是很确定

<img width="521" alt="2024-04-02_175400" src="https://github.com/cmdparkour/vue-admin-box/assets/39702760/09684d08-cf5f-43dc-a54f-4a2c883049a0">

**Comment by cmdparkour** [comment]
可以参照一下业务表格页面的代码，里面有详细的请求示例
